# Generated by Django 5.1.3 on 2024-12-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_address', models.CharField(max_length=50)),
                ('branch_IP', models.CharField(max_length=50)),
                ('branch_Shifts', models.CharField(max_length=50)),
                ('branch_emps', models.CharField(max_length=50)),
            ],
        ),
    ]
