# Generated by Django 5.1.3 on 2024-12-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0002_employee_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=str, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
