# Generated by Django 5.1.3 on 2024-12-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0003_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
