# Generated by Django 5.1.3 on 2024-12-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0005_alter_employee_branch_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password1',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password2',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
