# Generated by Django 5.1.3 on 2024-12-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0007_alter_shift_shift_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminSide.branch'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50),
        ),
    ]
