# Generated by Django 5.1.3 on 2024-12-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0008_alter_shift_shift_branch_alter_shift_shift_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_shift',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
