# Generated by Django 5.1.3 on 2024-12-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0009_remove_shift_employees_employee_assigned_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_Shifts',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_emps',
        ),
    ]
