# Generated by Django 5.1.3 on 2024-12-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0012_alter_employee_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
    ]
